# Generated by Django 2.2.2 on 2019-09-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenrAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menuId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SysAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=10)),
                ('genradmins', models.ManyToManyField(to='usermnge.GenrAdmin')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roleId', models.IntegerField()),
                ('menus', models.ManyToManyField(to='usermnge.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='NmlUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=10)),
                ('pros', models.ManyToManyField(to='usermnge.Pro')),
                ('roles', models.ManyToManyField(to='usermnge.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nmlusers', models.ManyToManyField(to='usermnge.NmlUser')),
                ('pros', models.ManyToManyField(to='usermnge.Pro')),
                ('roles', models.ManyToManyField(to='usermnge.Role')),
            ],
        ),
        migrations.AddField(
            model_name='genradmin',
            name='groups',
            field=models.ManyToManyField(to='usermnge.Group'),
        ),
        migrations.AddField(
            model_name='genradmin',
            name='nmlusers',
            field=models.ManyToManyField(to='usermnge.NmlUser'),
        ),
        migrations.AddField(
            model_name='genradmin',
            name='pros',
            field=models.ManyToManyField(to='usermnge.Pro'),
        ),
        migrations.AddField(
            model_name='genradmin',
            name='roles',
            field=models.ManyToManyField(to='usermnge.Role'),
        ),
    ]
